title: Creating and Deploying a Static Website
email: jversoza@cs.nyu.edu

tagline: "This time, it's personal!"

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../resources/lib"
slides_img_prefix: "../resources/img"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]
